backend:
  name: git-gateway
  branch: main

# when using the default proxy server port
local_backend: true

media_folder: content/img
public_folder: /img

collections:
  - name: 'category'
    identifier_field: 'name'
    label: 'Categories'
    label_singular: 'Category'
    folder: 'content/categories'
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    fields:
      - { label: 'Category Name', name: 'name', widget: 'string' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
    editor:
      preview: false

  - name: 'nutritionalFacts'
    identifier_field: 'key'
    label: 'Nutritional Facts'
    label_singular: 'Nutritional Fact'
    folder: 'content/nutritionalFacts'
    create: true
    path: '{{slug}}/index'
    fields:
      - { label: 'Key', name: 'key', widget: 'string' }
    editor:
      preview: false

  - name: 'monograph'
    label: 'Monographs'
    label_singular: 'Monograph'
    folder: 'content/monographs'
    create: true
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    fields:
      - { label: 'Monograph Title', name: 'title', widget: 'string' }
      - {
          label: 'Category',
          name: 'category',
          widget: 'relation',
          collection: 'category',
          value_field: 'name',
          search_fields: ['name'],
          display_fields: ['name'],
        }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Gallery',
          label_singular: 'Image',
          name: 'gallery',
          widget: 'list',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
      - { label: 'Creation Date', name: 'createdAt', widget: 'datetime' }
      - { label: 'Last Update', name: 'updatedAt', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Nutrition Facts'
        label_singular: 'Nutrition Fact'
        name: 'nutritionFacts'
        widget: 'list'
        fields:
          - label: 'Name'
            name: 'name'
            widget: 'relation'
            collection: 'nutritionalFacts'
            value_field: 'key'
            search_fields: ['key']
            display_fields: ['key']
          - label: 'Value'
            name: 'value'
            widget: 'string'
          - label: 'Unit'
            name: 'unit'
            widget: 'select'
            options: ['g', 'mg', 'µg', 'kcal', '%', 'u.i.']
